In [1]:
import pandas as pd

import numpy as np

In [2]:
train = pd.read_csv('train_cleaned.csv', dtype={'StateHoliday': str}, parse_dates=['Date'])

test = pd.read_csv('test_cleaned.csv', dtype={'StateHoliday': str}, parse_dates=['Date'])

In [3]:
print(train['Date'].dtype, test['Date'].dtype)

datetime64[ns] datetime64[ns]

In [4]:
train['StateHoliday'].map(type).value_counts()

StateHoliday
<class 'str'>    1017209
Name: count, dtype: int64

In [5]:
# One row per store, built from train only

stores = train.drop_duplicates('Store')[['Store', 'StoreType', 'Assortment', 'CompetitionDistance']]

print("Stores:", len(stores), "| null distance:", stores['CompetitionDistance'].isna().sum())

Stores: 1115 | null distance: 3

In [6]:
# Segment medians from observed values only

seg_median = stores.groupby(['StoreType', 'Assortment'])['CompetitionDistance'].agg(['median', 'count'])

seg_median

                      median  count
StoreType Assortment
a         a           1560.0    381
          c           2320.0    220
b         a           1180.0      7
          b            860.0      9
          c           1210.0      1
c         a           1270.0     77
          c           2100.0     71
d         a           4385.0    126
          c           5345.0    220

In [7]:
med = stores.groupby(['StoreType', 'Assortment'])['CompetitionDistance'].median()

med

StoreType  Assortment
a          a             1560.0
           c             2320.0
b          a             1180.0
           b              860.0
           c             1210.0
c          a             1270.0
           c             2100.0
d          a             4385.0
           c             5345.0
Name: CompetitionDistance, dtype: float64

In [8]:
for df in (train, test):
    df['CompetitionDistance_missing'] = df['CompetitionDistance'].isna().astype(int)
    fill = df.set_index(['StoreType', 'Assortment']).index.map(med)
    df['CompetitionDistance'] = df['CompetitionDistance'].fillna(pd.Series(fill, index=df.index))

for name, df in (('train', train), ('test', test)):
    print(name, "nulls:", df['CompetitionDistance'].isna().sum(),
          "| flagged rows:", df['CompetitionDistance_missing'].sum())
    print(df[df['CompetitionDistance_missing'] == 1].groupby('Store')['CompetitionDistance'].agg(['first', 'count']))

train nulls: 0 | flagged rows: 2642
        first  count
Store
291    4385.0    942
622    2320.0    942
879    4385.0    758
test nulls: 0 | flagged rows: 96
        first  count
Store
622    2320.0     48
879    4385.0     48

## CompetitionDistance imputation

**What:** Filled the 3 stores with missing CompetitionDistance (291, 622, 879) with their StoreType×Assortment segment median, and added a `CompetitionDistance_missing` flag (1 = filled, 0 = observed).

**Why:** Linear regression and sklearn's random forest cannot take NaN. A global median (~2,325) would understate d/a stores, whose median is 4,385. Dropping the stores would lose 2,642 train rows, and the test set contains stores 622 and 879. A placeholder like 999999 would wrongly claim "no competitor". The flag keeps the filled value visible as a guess.

**How:** Built a one-row-per-store view from train (1,115 stores). Computed segment medians from observed values only: d/a = 4,385 (n=126), a/c = 2,320 (n=220). Applied the same medians to train and test. The flag was created before filling.

**Validation:**
- 0 nulls remain in train and test.
- Train flagged rows = 2,642 (942 + 942 + 758), matching Stage 1.
- Test flagged rows = 96 (stores 622 and 879, 48 days each). Store 291 is not in the test set.

**Limits:** Stores 291 and 879 get the same value although EDA showed they sit at opposite ends of d/a sales. The fill approximates a typical d/a store and does not recover the true distance.

In [9]:
for df in (train, test):
    df['CompetitionDistance_log'] = np.log1p(df['CompetitionDistance'])

for name, df in (('train', train), ('test', test)):
    print(name, "nulls:", df['CompetitionDistance_log'].isna().sum())
    print(df['CompetitionDistance_log'].describe().round(3))

train nulls: 0
count    1017209.000
mean           7.645
std            1.557
min            3.045
25%            6.567
50%            7.754
75%            8.837
max           11.237
Name: CompetitionDistance_log, dtype: float64
test nulls: 0
count    41088.000
mean         7.620
std          1.536
min          3.045
25%          6.581
50%          7.794
75%          8.770
max         11.237
Name: CompetitionDistance_log, dtype: float64

In [10]:
# imputed stores should map to log1p of their fill values

print(np.log1p([4385, 2320]).round(3))

print(train[train['CompetitionDistance_missing'] == 1].groupby('Store')['CompetitionDistance_log'].first().round(3))

[8.386 7.75 ]
Store
291    8.386
622    7.750
879    8.386
Name: CompetitionDistance_log, dtype: float64

## CompetitionDistance log transform

**What:** Added `CompetitionDistance_log = log1p(CompetitionDistance)` to train and test. Models will use this column; the raw column stays in the dataframe but is excluded from the model feature list.

**Why:** Raw distance is right-skewed (mean 5,405 vs median 2,325), which would let a few far-away competitors dominate a linear model. log1p is monotonic, so trees are unaffected. One shared column avoids duplicate features and model-specific pipelines.

**How:** Applied np.log1p after the imputation step, so filled values are transformed like observed ones.

**Validation:**
- 0 nulls in train and test.
- Range 3.045–11.237 in both files; test sits inside the train range.
- Imputed stores map correctly: 291 and 879 = 8.386, 622 = 7.750.
- Mean 7.645 and median 7.754 show the skew is largely removed.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41088 entries, 0 to 41087
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Id                           41088 non-null  int64
 1   Store                        41088 non-null  int64
 2   DayOfWeek                    41088 non-null  int64
 3   Date                         41088 non-null  datetime64[ns]
 4   Open                         41088 non-null  float64
 5   Promo                        41088 non-null  int64
 6   StateHoliday                 41088 non-null  object
 7   SchoolHoliday                41088 non-null  int64
 8   StoreType                    41088 non-null  object
 9   Assortment                   41088 non-null  object
 10  CompetitionDistance          41088 non-null  float64
 11  CompetitionOpenSinceMonth    25872 non-null  float64
 12  CompetitionOpenSinceYear     25872 non-null  float64
 13  Promo2                       41088 non-null  int64
 14  Promo2SinceWeek              23856 non-null  float64
 15  Promo2SinceYear              23856 non-null  float64
 16  PromoInterval                23856 non-null  object
 17  competition_open_date_known  41088 non-null  int64
 18  CompetitionDistance_missing  41088 non-null  int64
 19  CompetitionDistance_log      41088 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(8), object(4)
memory usage: 6.3+ MB

In [12]:
df.dtypes

Id                                      int64
Store                                   int64
DayOfWeek                               int64
Date                           datetime64[ns]
Open                                  float64
Promo                                   int64
StateHoliday                           object
SchoolHoliday                           int64
StoreType                              object
Assortment                             object
CompetitionDistance                   float64
CompetitionOpenSinceMonth             float64
CompetitionOpenSinceYear              float64
Promo2                                  int64
Promo2SinceWeek                       float64
Promo2SinceYear                       float64
PromoInterval                          object
competition_open_date_known             int64
CompetitionDistance_missing             int64
CompetitionDistance_log               float64
dtype: object

In [13]:
for df in (train, test):
    df['Year'] = df['Date'].dt.year
    df['Month'] = df['Date'].dt.month
    df['WeekOfYear'] = df['Date'].dt.isocalendar().week.astype(int)
    df['IsWeekend'] = (df['DayOfWeek'] >= 6).astype(int)

In [14]:
for name, df in (('train', train), ('test', test)):
    print(name, df['Date'].min().date(), df['Date'].max().date())
    print('-'*30)
    print(df[['Year', 'Month', 'WeekOfYear', 'IsWeekend']].isna().sum().to_dict())
    print('-'*30)
    print(df.groupby('Year')['Month'].agg(['min', 'max']).T)
    print('-'*30)
    print("WeekOfYear range:", df['WeekOfYear'].min(), df['WeekOfYear'].max())

train 2013-01-01 2015-07-31
------------------------------
{'Year': 0, 'Month': 0, 'WeekOfYear': 0, 'IsWeekend': 0}
------------------------------
Year  2013  2014  2015
min      1     1     1
max     12    12     7
------------------------------
WeekOfYear range: 1 52
test 2015-08-01 2015-09-17
------------------------------
{'Year': 0, 'Month': 0, 'WeekOfYear': 0, 'IsWeekend': 0}
------------------------------
Year  2015
min      8
max      9
------------------------------
WeekOfYear range: 31 38

In [15]:
train.groupby('DayOfWeek')['IsWeekend'].mean()

DayOfWeek
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    1.0
7    1.0
Name: IsWeekend, dtype: float64

## Basic calendar features

**What:** Added Year, Month, WeekOfYear (ISO) and IsWeekend (DayOfWeek >= 6) to train and test.

**Why:** Month captures the confirmed December peak and January low. WeekOfYear gives finer seasonal position. IsWeekend flags Saturday/Sunday, which are structurally different (no promo; Sunday mostly closed). All are derived from Date only, so no leakage.

**How:** pandas dt accessors on the parsed Date column.

**Validation:**
- 0 nulls in both files.
- Train 2013-01-01 to 2015-07-31; 2015 months 1–7 (partial year).
- Test 2015-08-01 to 2015-09-17, weeks 31–38.
- IsWeekend = 0 for days 1–5, 1 for days 6–7.

**Open items:**
- Year may not generalize: 2015 is partial, and trees cannot extrapolate. To be tested in Part B.
- DayOfWeek is coded 1–7; linear models need an encoding decision (next step).

In [16]:
sh_map = {'0': 0, 'a': 1, 'b': 2, 'c': 3}

for df in (train, test):
    df['StateHoliday_code'] = df['StateHoliday'].map(sh_map)

In [17]:
for name, df in (('train', train), ('test', test)):
    print(name, "nulls:", df['StateHoliday_code'].isna().sum())
    print(df.groupby(['StateHoliday', 'StateHoliday_code']).size())

train nulls: 0
StateHoliday  StateHoliday_code
0             0                    986159
a             1                     20260
b             2                      6690
c             3                      4100
dtype: int64
test nulls: 0
StateHoliday  StateHoliday_code
0             0                    40908
a             1                      180
dtype: int64

In [18]:
raw = pd.read_csv('train_cleaned.csv', dtype={'StateHoliday': str}, keep_default_na=False,
                  usecols=['Store', 'Date', 'Open', 'StateHoliday'])
print(raw['StateHoliday'].value_counts(dropna=False))
print("NaN after normal read:", train['StateHoliday'].isna().sum())

StateHoliday
0    986159
a     20260
b      6690
c      4100
Name: count, dtype: int64
NaN after normal read: 0

In [19]:
train['StateHoliday'].map(type).value_counts()

StateHoliday
<class 'str'>    1017209
Name: count, dtype: int64

In [20]:
for df in (train, test):
    df['StateHoliday'] = df['StateHoliday'].astype(str)
    df['StateHoliday_code'] = df['StateHoliday'].map(sh_map)

In [21]:
for name, df in (('train', train), ('test', test)):
    print(name, "nulls:", df['StateHoliday_code'].isna().sum())
    print(df['StateHoliday'].value_counts())

train nulls: 0
StateHoliday
0    986159
a     20260
b      6690
c      4100
Name: count, dtype: int64
test nulls: 0
StateHoliday
0    40908
a      180
Name: count, dtype: int64

## StateHoliday encoding

**What:** Added `StateHoliday_code` (0, a, b, c → 0, 1, 2, 3). The string column stays but is excluded from the model features. Raw columns stay in the saved table; one-hot encoding is applied only inside the linear model's pipeline.

**Why:** sklearn's random forest cannot read strings. Trees can use the integer code; linear regression needs one-hot, applied at fit time so all models share one table.

**Problem found:** The first mapping left 393,216 train rows null. In memory, those rows held the integer 0 and not the string '0' (393,216 int vs 623,993 str). The file on disk was clean (986,159 '0').

**Fix:** Converted StateHoliday to str in train and test before mapping.

**Validation:**
- 0 nulls in both files.
- Train: 986,159 / 20,260 / 6,690 / 4,100 for 0, a, b, c.
- Test: 40,908 / 180 (41,088 total).

**Likely cause (inference):** mixed-type chunked reading in pandas. To be confirmed.

In [22]:
for name, df in (('train', train), ('test', test)):
    print(name, "Promo nulls:", df['Promo'].isna().sum())
    print(df.groupby('DayOfWeek')['Promo'].mean().round(4).to_dict())
    print("Weekend rows with Promo=1:", ((df['IsWeekend'] == 1) & (df['Promo'] == 1)).sum())

train Promo nulls: 0
{1: 0.5373, 2: 0.5326, 3: 0.5326, 4: 0.5319, 5: 0.5319, 6: 0.0, 7: 0.0}
Weekend rows with Promo=1: 0
test Promo nulls: 0
{1: 0.5714, 2: 0.5714, 3: 0.5714, 4: 0.5714, 5: 0.5, 6: 0.0, 7: 0.0}
Weekend rows with Promo=1: 0

## Promo and Promo × StoreType

**What:** Promo is used directly as a feature. The Promo × StoreType interaction is built only inside the linear model's pipeline (3B.3). Trees learn it through splits.

**Why:** EDA lift varies by format (a 43.96%, d 36.5%, c 34.0%, b 10.25% with 17 stores). Linear regression cannot learn this without interaction columns; trees can. Keeping one raw table avoids duplicate columns and drift between models. Separate per-StoreType models were rejected: type b is too thin.

**Validation:**
- 0 Promo nulls in train and test.
- Promo rate is 0.0 on Saturday and Sunday in both files; 0 weekend rows with Promo=1.
- No Promo × IsWeekend column is built (it would be all zeros).

**Assumption:** Promo is known at prediction time because promotions are scheduled in advance.

**Caution:** The StoreType b interaction rests on 17 stores. Do not read it as a clean causal effect.

In [23]:
import datetime as dt

mabbr = {1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'May',6:'Jun',7:'Jul',8:'Aug',
         9:'Sept',10:'Oct',11:'Nov',12:'Dec'}

In [24]:
st = train[train['Promo2'] == 1].drop_duplicates('Store')[['Store', 'Promo2SinceYear', 'Promo2SinceWeek']]

start_map = {r.Store: pd.Timestamp(dt.date.fromisocalendar(int(r.Promo2SinceYear), int(r.Promo2SinceWeek), 1))
             for r in st.itertuples()}

In [25]:
for df in (train, test):
    start = df['Store'].map(start_map)
    df['Promo2_enrolled'] = ((df['Promo2'] == 1) & (df['Date'] >= start)).astype(int)
    df['Promo2_round_start_month'] = 0
    for iv in df['PromoInterval'].dropna().unique():
        months = [m for m, a in mabbr.items() if a in iv.split(',')]
        df.loc[(df['PromoInterval'] == iv) & df['Month'].isin(months), 'Promo2_round_start_month'] = 1
    df['Promo2_round_start_month'] *= df['Promo2_enrolled']

In [26]:
print(sorted(train['PromoInterval'].dropna().unique()))

['Feb,May,Aug,Nov', 'Jan,Apr,Jul,Oct', 'Mar,Jun,Sept,Dec']

In [27]:
for name, df in (('train', train), ('test', test)):

    print(name, df[['Promo2_enrolled', 'Promo2_round_start_month']].isna().sum().to_dict())

    print(df.groupby('Promo2')[['Promo2_enrolled', 'Promo2_round_start_month']].mean().round(3))

    print("B > A rows:", (df['Promo2_round_start_month'] > df['Promo2_enrolled']).sum())

    print("Promo2=1 but not enrolled:", ((df['Promo2'] == 1) & (df['Promo2_enrolled'] == 0)).sum())

train {'Promo2_enrolled': 0, 'Promo2_round_start_month': 0}
        Promo2_enrolled  Promo2_round_start_month
Promo2
0                 0.000                     0.000
1                 0.863                     0.299
B > A rows: 0
Promo2=1 but not enrolled: 69630
test {'Promo2_enrolled': 0, 'Promo2_round_start_month': 0}
        Promo2_enrolled  Promo2_round_start_month
Promo2
0                   0.0                     0.000
1                   1.0                     0.219
B > A rows: 0
Promo2=1 but not enrolled: 0

## Promo2 features

**What:** Built two features, both 0 (never null) where a store has no Promo2:
- `Promo2_enrolled` = 1 when the store participates in Promo2 AND the date is on or after its Promo2 start week.
- `Promo2_round_start_month` = 1 when the store is enrolled AND the current month is one of its PromoInterval start months.

**Why (plain words):** Promo2 is a store-level programme. The raw columns are blank for non-participants, which breaks linear regression and random forest. Also, a store that joined in 2014 was not on Promo2 in 2013, so a plain Promo2 flag would be wrong for those earlier days. The dataset says PromoInterval gives the months a round *starts*, but not how long it lasts. So I did not invent an "active" flag with an assumed length. A says "has the store joined?" and B says "does a round begin this month?" Neither assumes a duration. A "months since round start" feature was left as a later experiment.

**How:** Computed each store's start date from its ISO week once, mapped it onto the daily rows, and matched months using a custom month list because the file writes September as "Sept".

**Validation:**
- 0 nulls; both features are 0 for every Promo2=0 row.
- B never exceeds A.
- Train: 86.3% of Promo2 rows are enrolled; 69,630 Promo2 rows are before the start date and correctly 0.
- Train B is about 1/3 of enrolled rows, as expected for 1 start month in 3.
- Test: all Promo2 rows are enrolled; B = 0.219 because test only covers Aug and early Sep.

**Limits:** ISO weeks may differ from Rossmann's week numbering by a few days. Whether Promo2 actually raises sales is not claimed here; Part B tests it.

In [28]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41088 entries, 0 to 41087
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Id                           41088 non-null  int64
 1   Store                        41088 non-null  int64
 2   DayOfWeek                    41088 non-null  int64
 3   Date                         41088 non-null  datetime64[ns]
 4   Open                         41088 non-null  float64
 5   Promo                        41088 non-null  int64
 6   StateHoliday                 41088 non-null  object
 7   SchoolHoliday                41088 non-null  int64
 8   StoreType                    41088 non-null  object
 9   Assortment                   41088 non-null  object
 10  CompetitionDistance          41088 non-null  float64
 11  CompetitionOpenSinceMonth    25872 non-null  float64
 12  CompetitionOpenSinceYear     25872 non-null  float64
 13  Promo2                       41088 non-null  int64
 14  Promo2SinceWeek              23856 non-null  float64
 15  Promo2SinceYear              23856 non-null  float64
 16  PromoInterval                23856 non-null  object
 17  competition_open_date_known  41088 non-null  int64
 18  CompetitionDistance_missing  41088 non-null  int64
 19  CompetitionDistance_log      41088 non-null  float64
 20  Year                         41088 non-null  int32
 21  Month                        41088 non-null  int32
 22  WeekOfYear                   41088 non-null  int64
 23  IsWeekend                    41088 non-null  int64
 24  StateHoliday_code            41088 non-null  int64
 25  Promo2_enrolled              41088 non-null  int64
 26  Promo2_round_start_month     41088 non-null  int64
dtypes: datetime64[ns](1), float64(7), int32(2), int64(13), object(4)
memory usage: 8.2+ MB

In [29]:
test['Date'].nunique()

48

In [30]:
n_days = train['Date'].nunique()

cnt = train.groupby('Store').size()

print("days:", n_days, "| stores with fewer rows:", (cnt < n_days).sum())

days: 942 | stores with fewer rows: 181

In [31]:
cnt.value_counts().head()

942    934
758    180
941      1
Name: count, dtype: int64

In [32]:
d = train[train['Store'].isin(cnt[cnt < n_days].index)].sort_values(['Store', 'Date']).copy()

d

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,competition_open_date_known,CompetitionDistance_missing,CompetitionDistance_log,Year,Month,WeekOfYear,IsWeekend,StateHoliday_code,Promo2_enrolled,Promo2_round_start_month
1016107,13,2,2013-01-01,0,0,0,0,a,1,d,...,0,0,5.739793,2013,1,1,0,1,1,0
1014992,13,3,2013-01-02,3737,317,1,0,0,1,d,...,0,0,5.739793,2013,1,1,0,0,1,0
1013877,13,4,2013-01-03,3674,292,1,0,0,1,d,...,0,0,5.739793,2013,1,1,0,0,1,0
1012762,13,5,2013-01-04,3848,340,1,0,0,1,d,...,0,0,5.739793,2013,1,1,0,0,1,0
1011647,13,6,2013-01-05,4285,344,1,0,0,0,d,...,0,0,5.739793,2013,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5568,1109,1,2015-07-27,8082,622,1,1,0,0,c,...,1,0,8.157944,2015,7,31,0,0,1,1
4453,1109,2,2015-07-28,6478,543,1,1,0,0,c,...,1,0,8.157944,2015,7,31,0,0,1,1
3338,1109,3,2015-07-29,6212,500,1,1,0,0,c,...,1,0,8.157944,2015,7,31,0,0,1,1
2223,1109,4,2015-07-30,5520,466,1,1,0,0,c,...,1,0,8.157944,2015,7,31,0,0,1,1
1108,1109,5,2015-07-31,5263,515,1,1,0,0,c,...,1,0,8.157944,2015,7,31,0,0,1,1

In [33]:
d['gap'] = d.groupby('Store')['Date'].diff().dt.days

In [34]:
big = d[d['gap'] > 1].copy()

big['last_before_gap'] = big['Date'] - pd.to_timedelta(big['gap'], unit='D')

big

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,CompetitionDistance_log,Year,Month,WeekOfYear,IsWeekend,StateHoliday_code,Promo2_enrolled,Promo2_round_start_month,gap,last_before_gap
235277,13,4,2015-01-01,0,0,0,0,a,1,d,...,5.739793,2015,1,1,0,1,1,0,185.0,2014-06-30
235284,20,4,2015-01-01,0,0,0,0,a,1,d,...,7.758333,2015,1,1,0,1,1,1,185.0,2014-06-30
235286,22,4,2015-01-01,0,0,0,0,a,1,a,...,6.947937,2015,1,1,0,1,1,1,185.0,2014-06-30
235296,32,4,2015-01-01,0,0,0,0,a,1,a,...,7.976252,2015,1,1,0,1,1,0,185.0,2014-06-30
235300,36,4,2015-01-01,0,0,0,0,a,1,a,...,6.293419,2015,1,1,0,1,1,1,185.0,2014-06-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236358,1094,4,2015-01-01,0,0,0,0,a,1,d,...,7.775276,2015,1,1,0,1,1,1,185.0,2014-06-30
236366,1102,4,2015-01-01,0,0,0,0,a,1,a,...,6.746412,2015,1,1,0,1,1,1,185.0,2014-06-30
236368,1104,4,2015-01-01,0,0,0,0,a,1,d,...,5.564520,2015,1,1,0,1,1,1,185.0,2014-06-30
236371,1107,4,2015-01-01,0,0,0,0,a,1,a,...,7.244942,2015,1,1,0,1,1,1,185.0,2014-06-30
236373,1109,4,2015-01-01,0,0,0,0,a,1,c,...,8.157944,2015,1,1,0,1,1,1,185.0,2014-06-30

In [35]:
big.groupby(['last_before_gap', 'Date', 'gap']).size()

last_before_gap  Date        gap
2014-06-30       2015-01-01  185.0    180
dtype: int64

## Problem found: 180 stores have missing rows in 2014

**What we observed**
- The verified date range is 2013-01-01 to 2015-07-31, which is 942 days.
- 1,115 stores × 942 days = 1,050,330 expected rows. `train_cleaned.csv` has 1,017,209 rows, so 33,121 rows are missing.
- 934 stores have all 942 days. 180 stores have only 758 rows (942 − 184). One store has 941 rows, one day short.
- All 180 stores share one gap: their last row before it is 2014-06-30 and their next row is 2015-01-01. That is 184 missing days (2014-07-01 to 2014-12-31).
- 180 × 184 + 1 = 33,121, which matches the missing-row total exactly.

**Why this was missed**
- Stage 2 looked for long runs of `Open == 0` rows and found only stores 103 and 1081 (2013-01-01 to 2013-07-04). That finding still stands.
- The gap here is different: the rows do not exist at all. A search through `Open == 0` rows cannot detect absent rows.
- So the Stage 2 correction ("the 180-store gap does not exist") was wrong for missing rows. The original Stage 1 note (180 stores, 184 days) was correct about absent rows, though it was unverified at the time. The correction note should be added to `decision_log.md` and `eda_findings.md`.

**Why it matters for lag features**
- For these 180 stores, `lag_49` and `lag_56` land inside the gap for rows in early 2015. The 28-day rolling window (shifted by 48 days) is entirely inside the gap for rows up to about mid-February 2015.
- Earlier, we assumed cold start only occurs at the start of the data. That is not true; it also occurs after this gap.
- A row-position shift would silently pull the wrong day across the gap. Date-indexed lags are required.

**What it does not affect**
- Test lags point at June–July 2015, where every store has data.

**Open items (not yet checked)**
- The one store with 941 rows: which day is missing, and where?
- Whether the changed store mix from July 2014 affects the Stage 2 Dec 2013 vs Dec 2014 comparison.
- The Aug–Sep 2014 validation window contains only 935 stores.

In [36]:
full_idx = pd.date_range(train['Date'].min(), test['Date'].max())

wide = (train.assign(S=train['Sales'].where(train['Open'] == 1))
        .pivot(index='Date', columns='Store', values='S').reindex(full_idx))

present = (train.assign(P=1).pivot(index='Date', columns='Store', values='P')
           .reindex(full_idx).fillna(0))

In [37]:
grids = {
    'lag_49': wide.shift(49),
    'lag_56': wide.shift(56),
    'roll_mean_28': wide.shift(48).rolling(28, min_periods=1).mean(),
    'p49': present.shift(49).fillna(0),
    'p56': present.shift(56).fillna(0),
    'pwin': present.shift(48).rolling(28).sum().fillna(0),
}

In [38]:
feats = None

for name, g in grids.items():
    long = g.rename_axis('Date').reset_index().melt(id_vars='Date', var_name='Store', value_name=name)
    feats = long if feats is None else feats.merge(long, on=['Date', 'Store'])

feats['hist_absent'] = ((feats['p49'] == 0) | (feats['p56'] == 0) | (feats['pwin'] < 28)).astype(int)

In [39]:
feats = feats[['Date', 'Store', 'lag_49', 'lag_56', 'roll_mean_28', 'hist_absent']]

feats.head()

        Date Store  lag_49  lag_56  roll_mean_28  hist_absent
0 2013-01-01     1     NaN     NaN           NaN            1
1 2013-01-02     1     NaN     NaN           NaN            1
2 2013-01-03     1     NaN     NaN           NaN            1
3 2013-01-04     1     NaN     NaN           NaN            1
4 2013-01-05     1     NaN     NaN           NaN            1

In [40]:
first_open = train[train['Open'] == 1].groupby('Store')['Date'].min()

first_open.head()

Store
1   2013-01-02
2   2013-01-02
3   2013-01-02
4   2013-01-02
5   2013-01-02
Name: Date, dtype: datetime64[ns]

In [41]:
n_tr, n_te = len(train), len(test)

cols = ['lag_49', 'lag_56', 'roll_mean_28', 'hist_absent', 'cold_open']

train = train.drop(columns=cols, errors='ignore').merge(feats, on=['Store', 'Date'], how='left')

test = test.drop(columns=cols, errors='ignore').merge(feats, on=['Store', 'Date'], how='left')

assert len(train) == n_tr and len(test) == n_te

train

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,Month,WeekOfYear,IsWeekend,StateHoliday_code,Promo2_enrolled,Promo2_round_start_month,lag_49,lag_56,roll_mean_28,hist_absent
0,1,5,2015-07-31,5263,555,1,1,0,1,c,...,7,31,0,0,0,0,3695.0,5384.0,4560.681818,0
1,2,5,2015-07-31,6064,625,1,1,0,1,a,...,7,31,0,0,1,1,3539.0,4938.0,4909.956522,0
2,3,5,2015-07-31,8314,821,1,1,0,1,a,...,7,31,0,0,1,1,6181.0,9685.0,7259.636364,0
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,...,7,31,0,0,0,0,7889.0,10416.0,9784.826087,0
4,5,5,2015-07-31,4822,559,1,1,0,1,a,...,7,31,0,0,0,0,4329.0,5431.0,4719.869565,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1,a,...,1,1,0,1,0,0,NaN,NaN,NaN,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1,c,...,1,1,0,1,0,0,NaN,NaN,NaN,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1,a,...,1,1,0,1,0,0,NaN,NaN,NaN,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1,a,...,1,1,0,1,0,0,NaN,NaN,NaN,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1,d,...,1,1,0,1,1,0,NaN,NaN,NaN,1

In [42]:
test

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,...,Month,WeekOfYear,IsWeekend,StateHoliday_code,Promo2_enrolled,Promo2_round_start_month,lag_49,lag_56,roll_mean_28,hist_absent
0,1,1,4,2015-09-17,1.0,1,0,0,c,a,...,9,38,0,0,0,0,5020.0,3769.0,4409.166667,0
1,2,3,4,2015-09-17,1.0,1,0,0,a,a,...,9,38,0,0,1,0,8977.0,5702.0,6651.041667,0
2,3,7,4,2015-09-17,1.0,1,0,0,a,c,...,9,38,0,0,0,0,11560.0,9550.0,10165.125000,0
3,4,8,4,2015-09-17,1.0,1,0,0,a,a,...,9,38,0,0,0,0,8420.0,6109.0,6303.958333,0
4,5,9,4,2015-09-17,1.0,1,0,0,a,c,...,9,38,0,0,0,0,7539.0,6471.0,7055.291667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,41084,1111,6,2015-08-01,1.0,0,0,0,a,a,...,8,31,1,0,1,0,2840.0,2716.0,4877.363636,0
41084,41085,1112,6,2015-08-01,1.0,0,0,0,c,c,...,8,31,1,0,0,0,8026.0,8314.0,9805.227273,0
41085,41086,1113,6,2015-08-01,1.0,0,0,0,a,c,...,8,31,1,0,0,0,5106.0,5533.0,6502.434783,0
41086,41087,1114,6,2015-08-01,1.0,0,0,0,a,c,...,8,31,1,0,0,0,22490.0,22017.0,22436.434783,0
41087,41088,1115,6,2015-08-01,1.0,0,0,1,d,c,...,8,31,1,0,1,0,7736.0,6596.0,7380.227273,0

In [43]:
for df in (train, test):
    df['cold_open'] = ((df['Date'] - df['Store'].map(first_open)).dt.days < 76).astype(int)

In [44]:
gap_start = pd.Timestamp('2014-07-01')

print("train rows:", len(train))

print("hist_absent total:", train['hist_absent'].sum(),
      "| before 2014-07-01:", ((train['hist_absent'] == 1) & (train['Date'] < gap_start)).sum(),
      "| from 2014-07-01:", ((train['hist_absent'] == 1) & (train['Date'] >= gap_start)).sum())

print("cold_open total:", train['cold_open'].sum(),
      "| cold_open not already absent:", ((train['cold_open'] == 1) & (train['hist_absent'] == 0)).sum())

train rows: 1017209
hist_absent total: 97125 | before 2014-07-01: 83625 | from 2014-07-01: 13500
cold_open total: 86320 | cold_open not already absent: 2695

In [45]:
keep = train[(train['hist_absent'] == 0) & (train['cold_open'] == 0)]

print("rows that would remain:", len(keep), "| dropped:", len(train) - len(keep))

print("NaN share among remaining rows:", keep[['lag_49', 'lag_56', 'roll_mean_28']].isna().mean().round(3).to_dict())

print("test flags:", test[['hist_absent', 'cold_open']].sum().to_dict(),
      "| test NaN share:", test[['lag_49', 'lag_56', 'roll_mean_28']].isna().mean().round(3).to_dict())

rows that would remain: 917389 | dropped: 99820
NaN share among remaining rows: {'lag_49': 0.17, 'lag_56': 0.17, 'roll_mean_28': 0.0}
test flags: {'hist_absent': 0, 'cold_open': 0} | test NaN share: {'lag_49': 0.142, 'lag_56': 0.142, 'roll_mean_28': 0.0}

In [46]:
# spot check: store 1, 2015-03-10

chk = train[(train['Store'] == 1) & (train['Date'] == '2015-03-10')].iloc[0]

src = train[(train['Store'] == 1) & (train['Date'] == pd.Timestamp('2015-03-10') - pd.Timedelta(days=49))].iloc[0]

print("lag_49:", chk['lag_49'], "| actual 49 days earlier:", src['Sales'] if src['Open'] == 1 else 'closed')

lag_49: 3680.0 | actual 49 days earlier: 3680

sales_open = train.assign(S=train['Sales'].where(train['Open'] == 1)) \
                  .pivot(index='Date', columns='Store', values='S')

def fill_same_weekday(col, max_back=8):
    out = col.copy()
    for k in range(1, max_back + 1):
        shifted = sales_open.shift(49 + 7 * k)
        out = out.fillna(shifted)
    return out

for df in (train, test):
    df['lag_49_filled'] = df['lag_49'].isna().astype(int)
    df['lag_56_filled'] = df['lag_56'].isna().astype(int)
    df['lag_49'] = fill_same_weekday(df.set_index(['Store', 'Date'])['lag_49']).values
    df['lag_56'] = fill_same_weekday(df.set_index(['Store', 'Date'])['lag_56']).values

for name, df in (('train', train), ('test', test)):
    keep = df[(df['hist_absent'] == 0) & (df['cold_open'] == 0)]
    print(name, "lag nulls after fill:", keep[['lag_49', 'lag_56']].isna().sum().to_dict())
    print(name, "filled rows:", keep[['lag_49_filled', 'lag_56_filled']].sum().to_dict())
    print(name, "max lag age:", (49 + 7 * 8), "days")

chk = train[(train['Store'] == 1) & (train['Date'] == '2015-03-10')].iloc[0]
print("lag_49:", chk['lag_49'], "| filled:", chk['lag_49_filled'])

In [47]:
# sales_open = train.assign(S=train['Sales'].where(train['Open'] == 1)) \
#                   .pivot(index='Date', columns='Store', values='S')

# def fill_same_weekday(df, col, max_back=8):
#     out = df.set_index(['Store', 'Date'])[col].copy()
#     for k in range(1, max_back + 1):
#         shifted = sales_open.shift(49 + 7 * k)
#         long = (shifted.rename_axis('Date').reset_index()
#                 .melt(id_vars='Date', var_name='Store', value_name='S')
#                 .set_index(['Store', 'Date'])['S'])
#         out = out.fillna(long)
#     return out

In [48]:
# for df in (train, test):
#     df['lag_49_filled'] = df['lag_49'].isna().astype(int)
#     df['lag_56_filled'] = df['lag_56'].isna().astype(int)
#     df['lag_49'] = fill_same_weekday(df, 'lag_49').values
#     df['lag_56'] = fill_same_weekday(df, 'lag_56').values

In [49]:
# for name, df in (('train', train), ('test', test)):
#     keep = df[(df['hist_absent'] == 0) & (df['cold_open'] == 0)]
#     print(name, "lag nulls after fill:", keep[['lag_49', 'lag_56']].isna().sum().to_dict())
#     print(name, "filled rows:", keep[['lag_49_filled', 'lag_56_filled']].sum().to_dict())

In [50]:
# chk = train[(train['Store'] == 1) & (train['Date'] == '2015-03-10')].iloc[0]

# print("lag_49:", chk['lag_49'], "| filled:", chk['lag_49_filled'])

In [51]:
# out = train.set_index(['Store', 'Date'])['lag_49']

# shifted = sales_open.shift(49)

# long = (shifted.rename_axis('Date').reset_index()
#         .melt(id_vars='Date', var_name='Store', value_name='S')
#         .set_index(['Store', 'Date'])['S'])

# print("out index:", out.index.names, out.index.dtypes.to_dict())

In [52]:
# print("long index:", long.index.names, long.index.dtypes.to_dict())

In [53]:
# print("overlap:", len(out.index.intersection(long.index)))

In [54]:
# print("nulls in out:", out.isna().sum(), "| non-null in long:", long.notna().sum())

In [55]:
raw_sales = train.pivot(index='Date', columns='Store', values='Sales')

open_mask = train.pivot(index='Date', columns='Store', values='Open')

In [56]:
sales_open = train.assign(S=train['Sales'].where(train['Open'] == 1)) \
                  .pivot(index='Date', columns='Store', values='S')

In [57]:
def fill_same_weekday(df, col, max_back=8):
    out = df.set_index(['Store', 'Date'])[col].copy()
    for k in range(1, max_back + 1):
        shifted_sales = raw_sales.shift(49 + 7 * k)
        shifted_open = open_mask.shift(49 + 7 * k)
        long = (shifted_sales.where(shifted_open == 1)
                .rename_axis('Date').reset_index()
                .melt(id_vars='Date', var_name='Store', value_name='S')
                .set_index(['Store', 'Date'])['S'])
        out = out.fillna(long)
    return out

In [58]:
for df in (train, test):
    df['lag_49_filled'] = df['lag_49'].isna().astype(int)
    df['lag_56_filled'] = df['lag_56'].isna().astype(int)
    df['lag_49'] = fill_same_weekday(df, 'lag_49').values
    df['lag_56'] = fill_same_weekday(df, 'lag_56').values

In [59]:
print("train" in dir(), "sales_open" in dir(), type(train) if "train" in dir() else "no train", type(sales_open) if "sales_open" in dir() else "no sales_open")

True True <class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>

In [60]:
out = train.set_index(['Store', 'Date'])['lag_49']
shifted = sales_open.shift(49)
long = (shifted.rename_axis('Date').reset_index()
        .melt(id_vars='Date', var_name='Store', value_name='S')
        .set_index(['Store', 'Date'])['S'])
before = out.isna().sum()
filled = out.fillna(long)
after = filled.isna().sum()
print("before:", before, "| after:", after, "| reduced by:", before - after)
print("long non-null:", long.notna().sum())

before: 197278 | after: 197278 | reduced by: 0
long non-null: 797394

In [61]:
out = train.set_index(['Store', 'Date'])['lag_49']
shifted = sales_open.shift(49)
long = (shifted.rename_axis('Date').reset_index()
        .melt(id_vars='Date', var_name='Store', value_name='S')
        .set_index(['Store', 'Date'])['S'])

print("out index equals long index:", out.index.equals(long.index))
print("out sorted:", out.index.is_monotonic_increasing, "| long sorted:", long.index.is_monotonic_increasing)
print("out first 3:", out.index[:3].tolist())
print("long first 3:", long.index[:3].tolist())

# try reindexing long to out's exact index, then fill
long_aligned = long.reindex(out.index)
print("aligned non-null:", long_aligned.notna().sum())
filled = out.fillna(long_aligned)
print("before:", out.isna().sum(), "| after:", filled.isna().sum())

out index equals long index: False
out sorted: False | long sorted: True
out first 3: [(1, Timestamp('2015-07-31 00:00:00')), (2, Timestamp('2015-07-31 00:00:00')), (3, Timestamp('2015-07-31 00:00:00'))]
long first 3: [(1, Timestamp('2013-01-01 00:00:00')), (1, Timestamp('2013-01-02 00:00:00')), (1, Timestamp('2013-01-03 00:00:00'))]
aligned non-null: 790363
before: 197278 | after: 197278

In [62]:
for df in (train, test):
    df['lag_49_filled'] = df['lag_49'].isna().astype(int)
    df['lag_56_filled'] = df['lag_56'].isna().astype(int)
    df['lag_49'] = df['lag_49'].fillna(df['roll_mean_28'])
    df['lag_56'] = df['lag_56'].fillna(df['roll_mean_28'])

for name, df in (('train', train), ('test', test)):
    keep = df[(df['hist_absent'] == 0) & (df['cold_open'] == 0)]
    print(name, "lag nulls after fill:", keep[['lag_49', 'lag_56']].isna().sum().to_dict())
    print(name, "filled rows:", keep[['lag_49_filled', 'lag_56_filled']].sum().to_dict())

train lag nulls after fill: {'lag_49': 87, 'lag_56': 87}
train filled rows: {'lag_49_filled': 126727, 'lag_56_filled': 126793}
test lag nulls after fill: {'lag_49': 0, 'lag_56': 0}
test filled rows: {'lag_49_filled': 5827, 'lag_56_filled': 5827}

In [63]:
store_mean = train[train['Open'] == 1].groupby('Store')['Sales'].mean()

for df in (train, test):
    df['lag_49'] = df['lag_49'].fillna(df['Store'].map(store_mean))
    df['lag_56'] = df['lag_56'].fillna(df['Store'].map(store_mean))

for name, df in (('train', train), ('test', test)):
    keep = df[(df['hist_absent'] == 0) & (df['cold_open'] == 0)]
    print(name, "lag nulls after final fill:", keep[['lag_49', 'lag_56']].isna().sum().to_dict())

train lag nulls after final fill: {'lag_49': 0, 'lag_56': 0}
test lag nulls after final fill: {'lag_49': 0, 'lag_56': 0}

## Lag and rolling features

**What:** Built three features on a full daily calendar (one row per store per day, 2013-01-01 to 2015-09-17):
- `lag_49`: same store's sales 49 days earlier (same weekday), open days only.
- `lag_56`: same store's sales 56 days earlier, open days only.
- `roll_mean_28`: mean of the store's open-day sales over the 28 days ending 48 days before the target date.

All features use sales at least 48 days old, matching the fixed 48-day forecast horizon.

**Why (plain words):** Everything before this described the calendar, promo and store type, but not how well this specific store has been selling lately. Recent sales carry the store-specific level, which is usually the strongest forecasting signal. Closed days are excluded (Option B) so a closure doesn't look like zero demand. A 49/56-day lag keeps the weekday aligned; the 28-day mean gives a smoothed store level.

**Problem found mid-build:** 180 stores are missing 184 days of rows (2014-07-01 to 2014-12-31), plus one store missing one day. This was missed in Stage 2 because that analysis only looked at `Open == 0` rows, not absent rows. It means cold start also occurs after this gap, not just at the start of the data. See the correction notes.

**How:** Built a wide date×store grid from train, shifted it by 49/56/48 days, melted back to long form, and merged onto train/test. A `hist_absent` flag marks rows whose lag windows fall in the start-of-history period or the 2014 gap. A `cold_open` flag marks rows within 76 days of a store's first open day.

**Fill decision:** Cold-start and post-gap rows are dropped (99,820 rows, ~9.8%). Closed-day blanks in the lags are filled with `roll_mean_28` (Option D fallback), then with the store's overall mean open-day sales for the last 87 rows where even the rolling mean was blank. `lag_49_filled` and `lag_56_filled` flags mark filled rows.

**Validation:**
- Row counts unchanged: 1,017,209 train, 41,088 test.
- Spot check: store 1, 2015-03-10, lag_49 = 3,680, matching actual sales 49 days earlier.
- 0 nulls in lag_49 and lag_56 after final fill, in both files.
- Test has no hist_absent or cold_open flags; its 14.2% initial blank rate was closed-day blanks, now filled.
- Max lag age after fallback fill: 105 days (49 + 7×8), though in practice the rolling mean covers nearly all cases.

**Limits:** The fallback fill loses the same-weekday specificity for filled rows. The 87 rows needing the store-mean fallback likely cluster around stores 103/1081 (long 2013 closures), though not verified.

In [64]:
for df in (train, test):
    df['Segment'] = df['StoreType'] + '_' + df['Assortment']


seg_levels = sorted(train['Segment'].unique())

seg_map = {s: i for i, s in enumerate(seg_levels)}

In [65]:
for df in (train, test):
    df['Segment_code'] = df['Segment'].map(seg_map)

seg_map

{'a_a': 0,
 'a_c': 1,
 'b_a': 2,
 'b_b': 3,
 'b_c': 4,
 'c_a': 5,
 'c_c': 6,
 'd_a': 7,
 'd_c': 8}

In [66]:
print(train.groupby('Segment')['Store'].nunique().to_dict())

{'a_a': 381, 'a_c': 221, 'b_a': 7, 'b_b': 9, 'b_c': 1, 'c_a': 77, 'c_c': 71, 'd_a': 128, 'd_c': 220}

In [67]:
print("Assortment b outside StoreType b:", ((train['Assortment'] == 'b') & (train['StoreType'] != 'b')).sum())

Assortment b outside StoreType b: 0

In [68]:
for name, df in (('train', train), ('test', test)):
    print(name, "nulls:", df[['Segment', 'Segment_code']].isna().sum().to_dict())

train nulls: {'Segment': 0, 'Segment_code': 0}
test nulls: {'Segment': 0, 'Segment_code': 0}

In [69]:
print("test segments not in train:", set(test['Segment']) - set(train['Segment']))

test segments not in train: set()

## StoreType and Assortment encoding

**What:** Created one combined `Segment` column (StoreType_Assortment, for example `d_a`, `b_b`) and an integer `Segment_code` for tree models. The original `StoreType` and `Assortment` columns stay in the table but are not used as separate model features. `StoreType` is kept for the Promo × StoreType interaction in the linear pipeline.

**Why (plain words):** EDA showed that Assortment b exists only inside StoreType b, so the two columns are not independent. If a linear model got them as separate columns, it would split one segment's effect across two overlapping columns. One combined column describes each real store format exactly once. Trees get an integer code, and the linear model one-hot encodes the same column at fit time, so every model reads one shared table.

**How:** Joined the two columns into a string. The integer codes were built from the training segments only, so test cannot introduce a code the models haven't seen.

**Validation:**
- Nine segments exist: a_a, a_c, b_a, b_b, b_c, c_a, c_c, d_a, d_c.
- Store counts per segment add up to 1,115.
- 0 rows with Assortment b outside StoreType b, so the EDA finding holds on the actual data.
- 0 nulls in `Segment` and `Segment_code` in train and test.
- No test segment is missing from train.

**Limits:** The b segments cover only 17 stores (b_a 7, b_b 9, b_c 1). Their coefficients describe those stores, not a general format effect. The b_c level is a single store, so its coefficient mostly reflects that store's own sales level. Store-level differences are also carried by the lag features.